config/routes.rb
# -*- encoding : utf-8 -*-

DiagramaDeNolan::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

#= 1. user routes ==============================================================
  devise_for :users

#= 2. lecture request routes ===========================================================
  get "/solicitar-palestra" => "site#lecture_request", :as => :lecture_request
  post "/solicitar-palestra" => "site#send_lecture_request", :as => :send_lecture_request

#= 3. questionnaire routes =====================================================
  get  '/questionario' => 'site#responses_new', :as => :questionnaire
  post '/questionario/validar_respostas' => 'site#validate_responses', :as => :validate_responses
  post '/questionario' => 'site#responses_create', :as => :responses_create
  get  '/questionario/resultado' => 'site#result', :as => :result

#= 4. result routes ============================================================
  get '/questionario/:position' => 'site#result_redirector', :as => :result_redirector

#= 5. page routes ==============================================================
  get '/cities' => 'cities#index'

#= 6. page routes ==============================================================
  get '/:page' => 'site#page', :as => :page

  root :to => 'site#index'
end

app/controllers/site_controller.rb
# -*- encoding : utf-8 -*-
class SiteController < ApplicationController
  # Used to redirect a users that enters "nolan.estudantespelaliberdade.com.br"
  # based on his IP.

  before_filter :set_initial_locale, :except => [:responses_create, :send_lecture_request]

  def set_initial_locale
    (redirect_to "#{request.url}?locale=#{lookup}" and return) if request.url !~ /locale\=/
  end

  layout 'fb_redirector', :only => :result_redirector

  def index
  end

  # LECTURE REQUEST BEGIN

  def lecture_request
    @lecture_request = Page.find_by_indicator(Page::PAGES[:lecture])
    @lecture_request_form = LectureRequest.new

    raise ActionController::RoutingError unless @lecture_request.published
  end

  def send_lecture_request
    @lecture_request = Page.where('indicator = ?', Page::PAGES[:lecture]).first
    @lecture_request_form = LectureRequest.new(params[:lecture_request])

    if @lecture_request_form.save
      redirect_to(lecture_request_path,
        :notice => t('lecture.error_request'))
    else
      render :action => :lecture_request
    end
  end

  # LECTURE REQUEST END

  # QUESTIONNAIRE BEGIN

  def responses_new
    @questions_civil_liberties = Question.
      where('category = ?', Question::CATEGORY[:civil_liberties]).
      order('weight DESC').limit(5)
    @questions_economic_freendom = Question.
      where('category = ?', Question::CATEGORY[:economic_freedom]).
      order('weight DESC').limit(5)
    @participant = Participant.new
  end

  def validate_responses
    @current_step = params[:current_step]
    @responses = []
    params[:questionnaire][:responses].each do |question_index, response|
      @responses << Response.new(:response => response.last)
    end
    respond_to do |format|
      format.js
    end
  end

  def responses_create
    @participant = Participant.new(params[:questionnaire][:participant])
    @results = { :economic_score => 0, :civil_score => 0 }

    if @participant.valid?
      @questions_category_1 = Question.
        where('category = ?', Question::CATEGORY[:civil_liberties]).
        order('weight DESC').limit(5)
      @questions_category_2 = Question.
        where('category = ?', Question::CATEGORY[:economic_freedom]).
        order('weight DESC').limit(5)
      @responses = []

      @questions_category_1.each_with_index do |question, i|
        i += 1
        response = Response.new(
          :participant => @participant,
          :question => question,
          :response => params[:questionnaire][:responses]["question_#{i}"]
        )

        @responses << response
        @results[:civil_score] += response.response
      end

      @questions_category_2.each_with_index do |question, i|
        i += 6
        response = Response.new(
          :participant => @participant,
          :question => question,
          :response => params[:questionnaire][:responses]["question_#{i}"]
        )

        @responses << response
        @results[:economic_score] += response.response
      end

      @responses.each { |r| r.save }

      @participant.economic_freedom_score = @results[:economic_score]
      @participant.civil_liberty_score = @results[:civil_score]
      @participant.save
    end
  end

  def result
  end

  # QUESTIONNAIRE END

  # PAGE BEGIN

  def page
    Page.where('published = ?', true).each do |p|
      @page = p if p.title.parameterize == params[:page]
    end

    raise ActionController::RoutingError if @page.nil?
  end

  # PAGE END

  def result_redirector
    @position = params[:position]

    if params[:locale] == 'pt'
      @image = {
        :libertarian => '/assets/fb_libertarian.jpg',
        :left => '/assets/fb_left.jpg',
        :centrist => '/assets/fb_centrist.jpg',
        :right => '/assets/fb_right.jpg',
        :statist => '/assets/fb_statist.jpg'
      }
    else
      @image = {
        :libertarian => '/assets/fb_int_libertarian.jpg',
        :left => '/assets/fb_int_left.jpg',
        :centrist => '/assets/fb_int_centrist.jpg',
        :right => '/assets/fb_int_right.jpg',
        :statist => '/assets/fb_int_statist.jpg'
      }
    end
  end


  protected
  def lookup
    request.compatible_language_from(ActiveRecord::Base::Configuration.first.valid_langs)
  end
end

app/helpers/site_helper.rb
# -*- encoding : utf-8 -*-

module SiteHelper

  def answers_input question_index
    out = ''
    Response.answers_sorted_by_value.each do |answer, value|
      out +=
      "<span class=\"#{answer.to_s}\"><strong>
        <input id=\"questionnaire_responses_question_#{question_index}_#{value}\" type=\"radio\" value=\"#{value}\" name=\"questionnaire[responses][question_#{question_index}]\">
        <label class=\"collection_radio_buttons\" for=\"questionnaire_responses_question_#{question_index}_#{value}\"><span>#{t('quiz.' + answer.to_s)}</span></label>
      </strong></span>"
    end
    return out.html_safe
  end
end

app/views/site/_result.html.erb
<%
  case @participant.position_result

  when Participant::POSITIONS['Centrista']
    page = Page.find_by_indicator(Page::PAGES[:centrist_result])
    position = t('result.centrist')
    facebook_share = 'centrist'
    twitter_share = t('result.twitter.centrist')

  when Participant::POSITIONS['Libertário']
    page = Page.find_by_indicator(Page::PAGES[:libertarian_result])
    position = t('result.libertarian')
    facebook_share = 'libertarian'
    twitter_share = t('result.twitter.libertarian')

  when Participant::POSITIONS['Esquerda']
    page = Page.find_by_indicator(Page::PAGES[:left_result])
    position = t('result.left')
    facebook_share = 'left'
    twitter_share = t('result.twitter.left')

  when Participant::POSITIONS['Direita']
    page = Page.find_by_indicator(Page::PAGES[:right_result])
    position = t('result.right')
    facebook_share = 'right'
    twitter_share = t('result.twitter.right')

  when Participant::POSITIONS['Estatista']
    page = Page.find_by_indicator(Page::PAGES[:statist_result])
    position = t('result.statist')
    facebook_share = 'statist'
    twitter_share = t('result.twitter.statist')

  end
%>

<% twitter_share += " #{configuration.site_url} #{result_redirector_path(facebook_share)}" %>

<style>
  <% ips = ((10 - @participant.civil_liberty_score) * 17).round %>
  <% eps = ((10 - @participant.economic_freedom_score) * 17).round %>
  #result_diagram .nolan_diagram .dot {
    background: url("/assets/dot.png") no-repeat <%= 172 + ips - eps %>px <%= ips + eps %>px;
  }

  #result_diagram .nolan_diagram .alert {
    margin: <%= ips + eps - 8 %>px 0 0 <%= 208 + ips - eps %>px;
  }
</style>

<div id="result_box" class="page_box">
  <div id="result_diagram">
    <div class="nolan_diagram <%= Page::PAGES.index(page.indicator).to_s %>">
      <ul class="positions">
        <li class="libertarian_item"><%= t('result.libertarian') %></li>
        <li class="left_item"><%= t('result.left') %></li>
        <li class="centrist_item"><%= t('result.centrist') %></li>
        <li class="right_item"><%= t('result.right') %></li>
        <li class="statist_item"><%= t('result.statist') %></li>
      </ul>

      <div class="alert">
        <p class="civil_liberties">
          <strong><%= @participant.civil_liberty_score * 10 %>%</strong><br/>
          <%= t('result.civil_liberties') %>
        </p>

        <p class="economic_freedom">
          <strong><%= @participant.economic_freedom_score * 10 %>%</strong><br />
          <%= t('result.economic_freedom') %>
        </p>

        <p class="close">&times;</p>
      </div>

      <div class="dot"></div>
    </div>

    <div class="result_score">
      <p class="civil_liberties">
        <strong><%= @participant.civil_liberty_score * 10 %>%</strong><br/>
        <%= t('result.civil_liberties') %>
      </p>

      <p class="economic_freedom">
        <strong><%= @participant.economic_freedom_score * 10 %>%</strong><br />
        <%= t('result.economic_freedom') %>
      </p>
    </div>

    <p class="result_position">
      <%= t('result.message') %>:<br />
      <strong class="<%= Page::PAGES.index(page.indicator).to_s %>"><%= position %></strong>
    </p>

    <div class="result_share">
      <p><%= t('result.share') %></p>

      <p class="facebook">
        <a href="http://www.facebook.com/sharer.php?u=<%= configuration.site_url + result_redirector_path(facebook_share) %>" target="_blank"><span>Facebook</span></a>
      </p>

      <p class="twitter">
        <a href="http://twitter.com/home?status=<%= twitter_share %>" target="_blank">
          <span>Twitter</span>
        </a>
      </p>
    </div>

  </div>

  <div id="result_content">
    <h2><%= page.title_by_lang(I18n.locale) %></h2>

    <%= page.content_by_lang(I18n.locale).html_safe %>
  </div>
</div>

app/views/site/index.html.erb
<%= content_for :page_title do 'Principal' end %>

<%= content_for :page_id do 'index' end %>

<%= content_for :content do %>
  <div id="index_logo">
    <%= link_to content_tag(:span,
        "<span class=\"play\"></span>#{t('home.start_the_test')}".html_safe),
      questionnaire_path %>
  </div>
<% end %>

app/views/site/lecture_request.html.erb
<%= content_for :content do %>
  <div class="page_box">
    <h2><%= @lecture_request.title %></h2>

    <%= @lecture_request.content_by_lang(I18n.locale).html_safe %>

    <%= content_tag(:p, notice, :class => 'notice') if notice %>

    <%= simple_form_for(@lecture_request_form,
      :url => send_lecture_request_path, :locale => lookup) do |f| %>
      <div class="inputs">
        <%= f.input :name %>
        <%= f.input :email %>
        <%= f.input :phone %>
        <%= f.input :city %>
        <%= f.input :state, :collection => LectureRequest::BRAZILIAN_STATES %>
        <%= f.input :place, :as => :text %>
      </div>

      <div class="actions">
        <%= f.button :submit, t('lecture.submit'), :class => 'right' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/site/page.html.erb
<%= content_for :page_title do @page.title_by_lang(I18n.locale) end %>

<%= content_for :page_id do Page::PAGES.index(@page.indicator) end %>

<%= content_for :content do %>
  <div class="page_box page">
    <h2><%= @page.title_by_lang(I18n.locale) %></h2>

    <%= @page.content_by_lang(I18n.locale).html_safe %>
  </div>
<% end %>

app/views/site/responses_create.js.erb
<% unless @participant.errors.blank? %>
  if($('#participant_info p.error_notice').length == 0) {
    $('#participant_info > p:first').after(
      '<p class="error_notice">Por favor, preencha os campos corretamente.</p>'
    );
  }
  $('input.right').removeClass('loading');
  checkParticipantInfoValues();
<% else %>
  $('#questionnaire').html('<%= escape_javascript(render(:partial => 'result')) %>');

  var result_banner = $('#result_banner > ul').bxSlider({
    displaySlideQty: 3, controls: false
  });

  $('#result_banner .controls .after').click(function () {
    result_banner.goToPreviousSlide();
  });

  $('#result_banner .controls .before').click(function () {
    result_banner.goToNextSlide();
  });

  setTimeout(function () {
    $('#result_diagram .nolan_diagram .alert').fadeIn(600);
  }, 200);
<% end %>

<% ['name', 'email', 'city'].each do |field| %>
  <% unless @participant.errors[field].blank? %>
    $('.input.<%= field %>').addClass('field_with_errors');
    $('.input.<%= field %> span.error').remove();
    $('.input.<%= field %>').append(
      '<span class="error"><%= @participant.errors[field] %></span>'
    );
  <% else %>
    $('.input.<%= field %>').removeClass('field_with_errors');
    $('.input.<%= field %> span.error').remove();
  <% end %>
<% end %>

app/views/site/responses_new.html.erb
<%= content_for :page_id do 'questionnaire' end %>

<%= content_for :page_title do 'Questionário' end %>

<%= content_for :content do %>
  <div id="questionnaire">
    <%=simple_form_for('questionnaire',
      :url => responses_create_path, :remote => true, :locale => lookup) do |f| %>

      <%= f.simple_fields_for 'responses' do |r| %>
        <div id="questions_category_1" class="page_box">
          <h2><%= t('quiz.civil_questions') %></h2>

          <p class="question_answers_legend">
            <span><%= t('quiz.my_responses') %></span>
          </p>

          <ol class="questions">
            <% @questions_civil_liberties.each_with_index do |question, i| %>
              <% i += 1 %>

              <li id="question_<%= i %>" class="question">
                <p class="index"><span><%= i %></span></p>
                <p class="question_text">
                  <%= question.question_by_lang(I18n.locale) %>
                </p>
                <p class="question_answers"><%= answers_input i %></p>
              </li>
            <% end %>
          </ol>

          <p class="actions">
            <a class="questions_category_1 right inactive" href="javascript:void(0);">
              <%= t('quiz.economic_questions') %>
            </a>
          </p>
        </div>

        <div id="questions_category_2" class="page_box" style="display: none;">
          <h2><%= t('quiz.economic_questions') %></h2>

          <p class="question_answers_legend">
            <span><%= t('quiz.my_responses') %></span>
          </p>

          <ol class="questions">
            <% @questions_economic_freendom.each_with_index do |question, i| %>
              <% i += 6 %>

              <li id="question_<%= i %>" class="question">
                <p class="index"><span><%= i %></span></p>
                <p class="question_text">
                  <%= question.question_by_lang(I18n.locale) %>
                </p>
                <p class="question_answers"><%= answers_input i %></p>
              </li>
            <% end %>
          </ol>

          <p class="actions">
            <a class="previous left" href="javascript:void(0);">
              <%= t('quiz.civil_questions') %>
            </a>

            <a class="questions_category_2 right inactive" href="javascript:void(0);">
              <%= t('quiz.personal_data') %>
            </a>
          </p>
        </div>
      <% end %>

      <%= f.simple_fields_for @participant do |p| %>
        <div id="participant_info" class="page_box" style="display: none;">
          <h2><%= t('quiz.personal_data') %></h2>

          <p><%= t('quiz.alert') %></p>

          <div class="fields">
              <% if request.location.country == 'Brazil' %>
                <div class="input boolean optional">
                  <label for="not_brazilian" class="boolean optional control-label checkbox">
                    <%= check_box_tag 'not_brazilian', '', false, :class => 'boolean optional' %>
                    I'm not Brazilian
                  </label>
                </div>

                <%= p.input :name, :wrapper_html => { :class => 'name' } %>
                <%= p.input :email, :wrapper_html => { :class => 'email' } %>
                <%= p.input :country, :required => true, :priority => [], :input_html => {:value => 'Brazil'}, :wrapper_html => { :class => 'country hidden' } %>
                <%= p.input :city_token, :required => true, :wrapper_html => { :class => 'city' } %>
              <% else %>
                <%= p.input :name, :wrapper_html => { :class => 'name' } %>
                <%= p.input :email, :wrapper_html => { :class => 'email' } %>
                <%= p.input :country, :required => true, :wrapper_html => { :class => 'country' }, :input_html => { :value => request.location.country } %>
                <%= p.input :city_token, :required => true, :wrapper_html => { :class => 'city hidden' } %>
              <% end %>

            <%= p.input :receive_email %>
          </div>
          <p class="actions">
            <a class="previous left" href="javascript:void(0);">
              <%= t('quiz.economic_questions') %>
            </a>
            <%= f.submit t('quiz.get_result'), :class => 'inactive right' %>
          </p>
        </div>
      <% end %>

    <% end %>
  </div>
<% end %>

app/views/site/result_redirector.html.erb
<%= content_for :fb_meta do %>
  <meta property="og:title" content="<%= t('result.facebook.' + @position + '.title') %>" />
  <meta property="og:description" content="<%= t('result.facebook.' + @position + '.description') %>" />
  <meta property="og:url" content="<%= configuration.site_url + result_redirector_path(params[:position]) %>" />
  <meta property="og:image" content="<%= configuration.site_url + @image[@position.to_sym] %>" />
<% end %>

app/views/site/validate_responses.js.erb
<% if @responses.map(&:valid?).include? false %>
  var questionnaire_html = $('#questionnaire').html();
  if($('#questionnaire p.error_notice').length == 0) {
    $('#questionnaire').prepend("<p class=\"error_notice\">Por favor, responda todas as perguntas.</p>");
  }
  <% @responses.each_with_index do |response, i| %>
    <% i += 1 %>
    <% i += 5 if @current_step == '2' %>
    <% if response.valid? %>
      $('#question_<%= i %>').removeClass('error');
    <% else %>
      $('#question_<%= i %>').addClass('error');
    <% end %>
  <% end %>
<% else %>
  <% @responses.each_with_index do |response, i| %>
    <% i += 1 %>
    <% i += 5 if @current_step == '2' %>
    $('#question_<%= i %>').removeClass('error');
  <% end %>
  $('#questionnaire p.error_notice').remove();
  <% if @current_step == '1' %>
    $('#questions_category_1').hide();
    $('#questions_category_2').show();
  <% elsif @current_step == '2' %>
    $('#questions_category_2').hide();
    $('#participant_info').show();
  <% end %>
<% end %>