config/routes.rb
# -*- encoding : utf-8 -*-

DiagramaDeNolan::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

#= 1. user routes ==============================================================
  devise_for :users

#= 2. lecture request routes ===========================================================
  get "/solicitar-palestra" => "site#lecture_request", :as => :lecture_request
  post "/solicitar-palestra" => "site#send_lecture_request", :as => :send_lecture_request

#= 3. questionnaire routes =====================================================
  get  '/questionario' => 'site#responses_new', :as => :questionnaire
  post '/questionario/validar_respostas' => 'site#validate_responses', :as => :validate_responses
  post '/questionario' => 'site#responses_create', :as => :responses_create
  get  '/questionario/resultado' => 'site#result', :as => :result

#= 4. result routes ============================================================
  get '/questionario/:position' => 'site#result_redirector', :as => :result_redirector

#= 5. page routes ==============================================================
  get '/cities' => 'cities#index'

#= 6. page routes ==============================================================
  get '/:page' => 'site#page', :as => :page

  root :to => 'site#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="<%= I18n.locale %>" xmlns:fb="http://ogp.me/ns/fb#">
<head>
  <title><%= t('home.title') %> - <%= yield :page_title %></title>

  <% if configuration.keywords %>
    <meta content="<%= configuration.keywords %>" name="keywords" />
  <% end %>

  <% if configuration.description %>
    <meta content="<%= configuration.description %>" name="description" />
  <% end %>

  <% if configuration.google_analytics %>
    <script type="text/javascript">
      <%= configuration.google_analytics.html_safe %>
    </script>
  <% end %>

  <meta content='http://algorich.com.br' name='author' />

  <meta property="og:title" content="<%= t('home.title') %> - <%= t('facebook_share.title') %>" />
  <meta property="og:description" content="<%= t('facebook_share.description') %>" />
  <meta property="og:url" content="<%= configuration.site_url + '?locale=' + I18n.locale.to_s %>" />
  <meta property="og:image" content="<%= configuration.site_url + '/assets/facebook_size_logo.jpg' %>" />

  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

  <%= favicon_link_tag %>

  <%= stylesheet_link_tag 'application.css' %>
  <%= javascript_include_tag 'application.js' %>
  <%= csrf_meta_tag %>

  <% if configuration.google_analytics_page_tracker %>
    <script type="text/javascript">
      <%= configuration.google_analytics_page_tracker.html_safe %>
      $(function () {
          $('.class_click').live('click', function (){
              recordOutboundLink($(this), 'Links externos do Diagrama de Nolan', 'Clique em link externo');
          });
      });
    </script>
  <% end %>
</head>

<body id="<%= yield :page_id %>_page" class="<%= I18n.locale %>_lang">
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div id="wrapper">

  <div id="header_wrapper">
    <div id="header">
      <h1><%= t('home.title') %></h1>
      <h2><%= t('home.subtitle') %></h2>
    </div>
  </div>

  <div id="main_navigation_wrapper">
    <ul id="main_navigation">
      <li class="nolan_item <%= 'active' if request.fullpath == questionnaire_path %>">
        <%= link_to content_tag(:span, t('home.start_the_test')), questionnaire_path %>
      </li>

      <% page = Page.find_by_indicator(Page::PAGES[:about]) %>
      <% if (page.present? && page.published) %>
        <li class="about_item <%= 'active' if request.fullpath == page_path(page.title.parameterize) %>">
          <%= link_to content_tag(:span, page.title_by_lang(I18n.locale)),
            page_path(page.title.parameterize) %>
        </li>
      <% end %>

      <% page = Page.find_by_indicator(Page::PAGES[:lecture]) %>
      <% if (page.present? && page.published) %>
        <li class="talk_item <%= 'active' if request.fullpath == lecture_request_path %>">
          <%= link_to content_tag(:span, page.title_by_lang(I18n.locale)),
            lecture_request_path %>
        </li>
      <% end %>

      <% page = Page.find_by_indicator(Page::PAGES[:donate]) %>
      <% if (page.present? && page.published) %>
        <li class="donate_item <%= 'active' if request.fullpath == page_path(page.title.parameterize) %>">
          <%= link_to content_tag(:span, page.title_by_lang(I18n.locale)),
            page_path(page.title.parameterize) %>
        </li>
      <% end %>

      <li class="lang_item">
        <a href="javascript:void(0);"><span><%= t('home.lang') %></span></a>

        <div class="langs_wrapper">
          <ul class="langs">
            <% languages = { :ar => 'العربية', :zh => '中国的', :da => 'Dansk',
              :en => 'English', :es => 'Español', :eo => 'Esperanto',
              :fr => 'Français', :de => 'Deutsch', :he => 'עברית',
              :hi => 'हिंदी', :it => 'Italiano', :ja => '日本の',
              :pt => 'Português', :ru => 'Pусский', :sv => 'Svenskt',
              :tr => 'Türk' }
            %>

            <% (Configuration.first.valid_langs).each do |key| %>
              <li <%= 'class="active"'.html_safe if key.to_sym == I18n.locale %>>
                <%= link_to languages[key.to_sym], url_for(:locale => key.to_sym) %>
              </li>
            <% end %>
          </ul>
        </div>
      </li>

      <li class="share_item">
        <a href="javascript:void(0);"><span><%= t('home.share') %></span></a>

        <div class="social_networks_wrapper">
          <div class="social_networks">

            <!-- AddThis Button BEGIN -->
            <div class="addthis_toolbox addthis_default_style addthis_32x32_style" addthis:url="<%= configuration.site_url + '?locale=' + I18n.locale.to_s %>" addthis:title="<%= t('home.title') %> - <%= t('facebook_share.title') %>">
            <a class="addthis_button_facebook"></a>
            <a class="addthis_button_twitter"></a>
            <a class="addthis_button_email"></a>
            <a class="addthis_counter addthis_bubble_style"></a>
            <script type="text/javascript">
              var addthis_config = {
                   data_track_clickback: false
              };
            </script>
            </div>
            <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4fac36301da977f7"></script>
            <!-- AddThis Button END -->

          </div>
        </div>
      </li>
    </ul>
    <fb:like href="http://www.facebook.com/diagramadenolan" send="false" layout="button_count" width="110" show_faces="false"></fb:like>
  </div>


  <div id="content_wrapper">
    <div id="content">
      <%= yield :content %>
    </div>
  </div>

  <div id="footer_wrapper">
    <div id="footer">
      <% page = Page.find_by_indicator(Page::PAGES[:partners]) %>
      <% if (page.present? && page.published) %>
        <div id="partners_page_content"><%= page.content.html_safe %></div>
      <% end %>
      <div id="partners_info">
        <div class="partners">
          <h2><%= t('footer.execution') %></h2>

          <ul>
            <li><a href="http://www.ideias.org/" target="_blank">
              <%= image_tag '/assets/logo_ideias.png',
                :alt => 'Instituto para o Desenvolvimento Econômico, Institucional e Social',
                :size => '234x70' %>
            </a></li>
          </ul>
        </div>

        <% sponsors = Sponsor.all %>

        <% unless sponsors.empty? %>
          <div class="partners sponsors">
            <h2><%= t('footer.sponsors') %></h2>

            <ul>
              <% sponsors.each do |s| %>
                <li>

                <% if s.link %>
                  <a href="<%= s.link %>" target="_blank">
                    <% if s.image %>
                      <%= image_tag s.image.url(:thumb), :alt => s.name %>
                    <% else %>
                      <%= s.name %>
                    <% end %>
                  </a>
                <% else %>
                  <% if s.image %>
                    <%= image_tag s.image.url(:thumb), :alt => s.name %>
                  <% else %>
                    <%= s.name %>
                  <% end %>
                <% end %>

                </li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <% if (page.present? && page.published) %>
          <p><a id="partners_page_link" href="javascript:void(0);">
            <%= t('footer.sponsors_text') %>
          </a></p>
        <% end %>
      </div>

      <div id="institutional_info_wrapper">
        <div id="institutional_info">
          <ul id="social_network">
            <% if configuration.facebook.present? %>
              <li class="facebook_item"><a href="<%= configuration.facebook %>" target="_blank">Facebook</a></li>
            <% end %>
            <% if configuration.twitter.present? %>
              <li class="twitter_item"><a href="<%= configuration.twitter %>" target="_blank">Twitter</a></li>
            <% end %>
          </ul>

          <%= auto_link(simple_format(configuration.footer_by_lang(I18n.locale))).html_safe %>

          <a class="alg_logo alg_logo_gray" href="http://www.algorich.com.br/" target="_banck">
            <img src="http://media.algorich.com.br/web_algorich_logo_hor.png" alt="Algorich" width="121" height="28"><br>
            <%= t('footer.execution') %> Algorich
          </a>
        </div>
      </div>
    </div>
  </div>

</div>
</body>

</html>

app/views/layouts/fb_redirector.html.erb
<!DOCTYPE html>

<html lang="pt-BR">
<head>
  <title>Diagrama De Nolan - Resultado do teste</title>
  <meta content="<%= configuration.keywords %>" name="keywords" />
  <meta content="<%= configuration.description %>" name="description" />
  <meta content='http://algorich.com.br' name='author' />

  <%= yield :fb_meta %>

  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

  <%= csrf_meta_tag %>
</head>

<body>

  <script type="text/javascript">
    window.location.href = "<%= configuration.site_url + questionnaire_path %>";
  </script>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>

<html lang="pt-BR">

<head>
  <title>Diagrama de Nolan - Login</title>

  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta content='http://algorich.com.br' name='author' />

  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

  <%= stylesheet_link_tag 'login.css' %>

  <%= csrf_meta_tag %>
</head>

<body id="login_page">

  <!-- CONTENT BEGIN -->
  <div id="content_wrapper">
    <div id="content">
      <h1><%= image_tag '/assets/logo_login.png', :alt => 'Diagrama de Nolan', :size => '190x168' %></h1>
      <%= yield :content %>
    </div>
  </div>
  <!-- CONTENT END -->

</body>

</html>